include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    equal_elements_in_set: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    prefer_double_quotes: true
