name: benchmark_app
description: The example project for the fast_immutable_collections package.
publish_to: "none"
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

flutter:
  uses-material-design: true

dependencies:
  fast_immutable_collections_benchmarks:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.1
