name: Dart || Tests | Formatting | Analyzer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter

    steps:
      - uses: actions/checkout@v2

      - name: Changing channels so we have access to NNBD
        run: bash tool/flutter_beta.sh

      - name: Removing CI/CD unnecessary folders
        run: bash tool/delete_noncicd_dirs.sh

      - name: Adding the Flutter dependency only for CI
        run: bash tool/append_flutter.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Static Analysis (also installs inner packages' dependencies)
        run: bash tool/static_analysis.sh

      - name: Run tests
        run: flutter test --coverage --coverage-path=lcov.info

      - name: Run json_serializable e2e tests
        run: bash tool/test_json_serializable_codegen.sh

      - name: Upload Results to Codecov.io
        run: bash tool/codecov.sh
